In [1]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [4]:
from tensorflow.keras.layers import Input, Dense, SimpleRNN, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Keterangan
N = Jumlah sampel

T = Panjang sequence

D = jumlah fitur masukkan

M = Jumlah hidde unit

K = Jumlah output unit


In [5]:
# Membuat beberapa data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [7]:
# Membuat RNN
M = 5 #jumlah hidden unit
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x)

In [8]:
#Mendapatkan Output
Yhat = model.predict(X)
print(Yhat)

[[-0.1753972  0.2585571]]


In [9]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.layers[1].get_weights()

[array([[ 0.8587907 , -0.8040451 ,  0.23593003, -0.10300618, -0.4762214 ],
        [ 0.7216243 , -0.04635459, -0.42133003, -0.26511735, -0.6827851 ],
        [-0.1345135 ,  0.6523637 ,  0.80463904, -0.04362684, -0.39246154]],
       dtype=float32),
 array([[-0.07290804, -0.64570695, -0.24604686,  0.15792166, -0.7016185 ],
        [ 0.34465396,  0.6561101 ,  0.03461704, -0.06779085, -0.6670377 ],
        [ 0.3233415 , -0.24709567,  0.8757904 ,  0.2534118 , -0.05628285],
        [-0.7122398 ,  0.0570589 ,  0.4120754 , -0.5126584 , -0.23839879],
        [-0.51387036,  0.2971028 ,  0.03804966,  0.80214024, -0.05282453]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [11]:
# Mengecek shapes
# Sebaiknya membuat sense
# pertama output adalah input > hidden
# kedua output adalah hidden > hidden
# ketiga output adalah bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [12]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [14]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # satu dan hanya sampel
Yhats = [] 

for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo # hanya iterasi terakhir
    Yhats.append(y)
    
    #penting : masukkan h ke h_last
    h_last = h


#print output final
print(Yhats[-1])


[-0.17539725  0.25855712]
